---
- name: Provision an EC2 Instance
  hosts: local
  connection: local
  vars_files:
    - ../../vars.yml
  vars:
    - do_name: "gateway"
  tasks:
    - digital_ocean: >
        state=present
        command=ssh
        name="{{ do_ssh_name }}"
        ssh_pub_key="{{ do_ssh_pub_key }}"
        api_token={{ do_api_token }}
      register: do_droplet

    - digital_ocean: >
        state=active
        name={{ do_name }}
        size_id={{ do_size }}
        region_id={{ do_region }}
        image_id={{ do_image }}
        ssh_key_ids={{ do_droplet.ssh_key.id }}
        unique_name=yes
        api_token={{ do_api_token }}
        wait_timeout=600
      register: do_droplet

    - debug: msg="ID is {{ do_droplet.droplet.id }}"
    - debug: msg="IP is {{ do_droplet.droplet.ip_address }}"

    - name: Add the newly created instance(s) to the local host group
      local_action: lineinfile 
                    dest="./hosts" 
                    regexp={{ do_droplet.droplet.ip_address }} 
                    insertafter="[gateway]" line={{ do_droplet.droplet.ip_address }}

- name: Run Test Script
  hosts: gateway
  tasks:
    - shell: echo 'test script' #should change to test script
      args:
          chdir: /root
